    'use client';

    import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

    type Language = 'es' | 'en';

    interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    }

    const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

    const translations = {
    es: {
        // ... MANTENER TODO LO ANTERIOR (nav, etc) ...
        'nav.services': 'Servicios',
        'nav.about': 'Nosotros',
        'nav.results': 'Resultados',
        'nav.cases': 'Casos',
        'nav.process': 'Proceso',
        'nav.contact': 'Contacto',
        'nav.menu': 'Menú',
        'nav.book': 'Agendar Consulta',
        'nav.tooltips.services': 'Explora soluciones de automatización',
        'nav.tooltips.about': 'Conocé al equipo detrás',
        'nav.tooltips.results': 'Ver resultados de clientes',
        'nav.tooltips.cases': 'Ver nuestros casos y proyectos',
        'nav.tooltips.process': 'Entender nuestra metodología',
        'nav.tooltips.contact': 'Agendar consulta',

        // --- PORTFOLIO / CASOS ---
        'portfolio.title': 'Casos y proyectos',
        'portfolio.subtitle': 'Una selección de trabajos reales por rubro. Cada proyecto, su propio desafío y su propia solución.',
        'portfolio.home.title': 'Así convertimos problemas operativos en soluciones digitales',
        'portfolio.home.subtitle': 'Selección de proyectos entregados para reducir trabajo manual, conectar herramientas y mejorar operaciones.',
        'portfolio.home.cta': 'Ver todos los casos',
        'portfolio.featured': 'Casos destacados',
        'portfolio.more': 'Más proyectos',
        'case.featured': 'Caso destacado',
        'case.eyebrow': 'Caso de éxito',
        'case.client': 'Cliente',
        'case.challenge': 'El desafío',
        'case.solution': 'La solución',
        'case.services': 'Servicios',
        'case.result': 'Resultado',
        'case.view': 'Ver caso',
        'case.cta': 'Hablemos de tu proyecto',
        'case.back': 'Volver a los casos',
        'case.prev': 'Proyecto anterior',
        'case.next': 'Proyecto siguiente',
        'case.contact.eyebrow': 'Contacto',
        'case.contact.title': 'Trabajemos juntos',
        'case.contact.subtitle': 'Si llegaste hasta acá, escribinos y lo charlamos sin compromiso.',
        'case.contact.cta': 'Ponerse en contacto',

        // --- CAMBIO  (Hero Badge) ---
        // Antes decía: 'Transformación digital • Automatización • IA'
        'hero.badge': 'Automatización • IA • Desarrollo Web', 
        'hero.title.part1': 'Construí sistemas que',
        'hero.title.highlight': 'hacen escalar',
        'hero.title.part2': 'tu negocio',
        'hero.subtitle': 'Del cuello de botella al crecimiento, desde 7-14 días',
        'hero.cta.book': 'Agendar Llamada Estratégica',
        'hero.cta.work': 'Ver Nuestro Trabajo',

        // --- QUIÉNES SOMOS (anónimo, diferencial — NO servicios) ---
        'about.eyebrow': 'El equipo detrás de Digital Match Global',
        'about.title': 'Recuperá las horas que hoy se pierden en tareas manuales.',
        'about.subtitle': 'Ingeniería aplicada a tu día a día: automatizamos procesos, conectamos sistemas y construimos herramientas para que tu equipo trabaje con menos fricción.',
        'about.diff1.title': '+14 años',
        'about.diff1.desc': 'De experiencia en automatización, IA y desarrollo.',
        'about.diff2.title': 'Empresas y gobierno',
        'about.diff2.desc': 'Experiencia real en el sector privado y público.',
        'about.diff3.title': 'Seguridad y cumplimiento',
        'about.diff3.desc': 'Experiencia bajo ISO 9001 y compliance PCI-DSS en el tratamiento de datos.',
        'about.diff4.title': 'Certificados',
        'about.diff4.desc': 'En UiPath, Microsoft e IBM.',
        'about.tools_label': 'Stack tecnológico',
        'stack.subtitle': 'Cubrimos todo el pipeline, de la automatización a la nube.',
        'stack.rpa': 'Automatización / RPA',
        'stack.ai': 'IA & Datos',
        'stack.dev': 'Desarrollo',
        'stack.cloud': 'Cloud & Infraestructura',
        'stack.data': 'Bases de datos',
        'stack.integrations': 'Integraciones & APIs',

        // ... MANTENER RESTO DE CLAVES (keywords, proof, services, technical, etc) ...
        'keywords.ml': 'Aprendizaje Automático',
        'keywords.automation': 'Automatización de Procesos',
        'keywords.api': 'Integración de APIs',
        'keywords.cloud': 'Infraestructura en la Nube',
        'keywords.analytics': 'Análisis de Datos',
        'keywords.ai': 'Soluciones IA',
        'proof.m1.label': 'Años de Experiencia',
        'proof.m2.label': 'Procesos Automatizados',
        'proof.m3.label': 'Días del diagnóstico a la solución',
        'services.main_title': 'Nuestros Servicios',
        'services.main_subtitle': 'Soluciones integrales para escalar las operaciones de tu negocio',
        'services.cta_button': 'Ver Caso de Éxito',
        // --- Producto propio: MatchBot ---
        'services.matchbot.eyebrow': 'Producto propio',
        'services.matchbot.desc': 'MatchBot es nuestra plataforma de bots de WhatsApp con IA: cada empresa conecta su propio número y automatiza sus conversaciones. Construida sobre nuestra integración oficial como Tech Provider de Meta.',
        'services.matchbot.cta': 'Conocé MatchBot',
        'services.auto.title': 'Automatización de Procesos (RPA)',
        'services.auto.headline': 'Elimina el 80% de tareas manuales',
        'services.auto.desc': 'Bots RPA que transforman flujos repetitivos en sistemas que trabajan 24/7, sin intervención humana (UiPath · Rocketbot · Power Automate).',
        'services.auto.f1': 'Bots RPA a medida (UiPath · Rocketbot)',
        'services.auto.f2': 'Sincronización e integración de datos',
        'services.auto.f3': 'Notificaciones y correos automáticos',
        'services.auto.f4': 'Sistemas de generación de reportes',
        'services.ai.title': 'Asistentes IA',
        'services.ai.headline': 'Soporte al cliente automatizado 24/7',
        'services.ai.desc': 'Implementa chatbots inteligentes que manejan consultas, reservas y tickets de soporte automáticamente.',
        'services.ai.f1': 'Procesamiento de lenguaje natural (NLP)',
        'services.ai.f2': 'Integración multicanal (WhatsApp/Web)',
        'services.ai.f3': 'Entrenamiento personalizado con tus datos',
        'services.ai.f4': 'Panel de análisis y métricas',
        'services.web.title': 'Productos Web',
        'services.web.headline': 'Plataformas que generan ingresos',
        'services.web.desc': 'Construye aplicaciones web escalables y herramientas internas que impulsan el crecimiento y la eficiencia.',
        'services.web.f1': 'Desarrollo de MVP (desde 7-14 días)',
        'services.web.f2': 'Diseño adaptable a móviles',
        'services.web.f3': 'Integraciones API y de terceros',
        'services.web.f4': 'Seguridad y cumplimiento integrados',
        'services.consulting.title': 'Consultoría y Capacitación',
        'services.consulting.headline': 'Transformación digital y adopción de tecnología',
        'services.consulting.desc': 'Asesoramos y formamos a tu equipo: del diagnóstico de procesos a jornadas de capacitación en automatización e IA.',
        'services.consulting.f1': 'Diagnóstico de procesos y oportunidades (RPA/IA)',
        'services.consulting.f2': 'Hoja de ruta de transformación digital',
        'services.consulting.f3': 'Jornadas de capacitación a equipos',
        'services.consulting.f4': 'Adopción de IA y automatización',

        // --- Modelos de contratación ---
        'services.models.title': 'Cómo podés contratarnos',
        'services.models.subtitle': 'Elegí el formato que mejor se adapta a tu necesidad.',
        'services.models.project.title': 'Por proyecto',
        'services.models.project.desc': 'Solución llave en mano, con un MVP funcional desde 7-14 días según la complejidad.',
        'services.models.hourly.title': 'Por hora',
        'services.models.hourly.desc': 'Bolsa de horas para RPA, automatización y desarrollo, a demanda.',
        'services.models.consulting.title': 'Consultoría',
        'services.models.consulting.desc': 'Diagnóstico, arquitectura y hoja de ruta de transformación digital.',
        'services.models.training.title': 'Jornadas de capacitación',
        'services.models.training.desc': 'Formación a tu equipo en RPA, IA y adopción de tecnología.',

        // --- Certificaciones ---
        'certs.title': 'Certificaciones que nos avalan',
        'certs.subtitle': 'Formación oficial que respalda cómo trabajamos.',
        'certs.uipath': 'UiPath RPA Developer',
        'certs.rocketbot': 'Rocketbot Suite (RPA)',
        'certs.microsoft': 'Microsoft Azure AI',
        'certs.ibm': 'IBM Data Science',
        'certs.meta.title': 'Tech Provider verificado de Meta',
        'certs.meta.subtitle': 'Integración oficial con la API de WhatsApp Business — negocio verificado y App Review aprobado por Meta.',

        'technical.title': 'Cómo lo hacemos',
        'technical.subtitle': 'Estándares enterprise y resultados típicos en cada área de trabajo',
        'technical.outcomes_title': 'Resultados Típicos',
        'technical.auto.title': 'Automatización de Procesos',
        'technical.auto.desc': 'Elimina tareas repetitivas y optimiza operaciones con sistemas inteligentes.',
        'technical.auto.impact': 'Máxima Eficiencia Operativa', 
        'technical.auto.out1': 'Reduce la entrada manual de datos en un 90%',
        'technical.auto.out2': 'Corta tiempos de proceso de horas a minutos',
        'technical.auto.out3': 'Elimina el error humano en tareas de rutina',
        'technical.auto.out4': 'Libera a tu equipo para trabajo estratégico',
        'technical.ai.title': 'Asistentes IA',
        'technical.ai.desc': 'Implementa chatbots inteligentes y asistentes virtuales para atención 24/7.',
        'technical.ai.impact': 'Atención 24/7 Garantizada', 
        'technical.ai.out1': 'Maneja el 80% de consultas automáticamente',
        'technical.ai.out2': 'Reduce el tiempo de respuesta a segundos',
        'technical.ai.out3': 'Escala el soporte sin contratar más personal',
        'technical.ai.out4': 'Mejora la satisfacción del cliente',
        'technical.web.title': 'Productos Web',
        'technical.web.desc': 'Construye plataformas y herramientas internas que impulsan el crecimiento.',
        'technical.web.impact': 'Alto Rendimiento y SEO', 
        'technical.web.out1': 'Primer MVP desde 7-14 días, según complejidad',
        'technical.web.out2': 'Escalable a miles de usuarios',
        'technical.web.out3': 'Integración con sistemas existentes',
        'technical.web.out4': 'Optimizado para móviles y seguro',
        'faq.title': 'Preguntas Frecuentes',
        'faq.subtitle': 'Todo lo que necesitas saber sobre cómo trabajamos',
        'faq.q1.question': '¿Cuánto tiempo toma entregar un proyecto?',
        'faq.q1.answer': 'Depende de la complejidad: la mayoría de los proyectos empieza a entregarse a partir de 7-14 días desde el inicio. Seguimos una metodología ágil con actualizaciones diarias; en proyectos más grandes, la primera versión funcional llega en pocas semanas.',
        'faq.q1.stats': 'Primer MVP: desde 7-14 días',
        'faq.q2.question': '¿Cuál es su proceso de trabajo?',
        'faq.q2.answer': 'Comenzamos con una llamada estratégica, seguida de una especificación técnica. Desarrollamos en sprints con comunicación diaria. Tendrás acceso a un entorno de pruebas y la entrega final incluye documentación y capacitación.',
        'faq.q2.stats': 'Comunicación diaria durante el proyecto',
        'faq.q3.question': '¿Ofrecen soporte post-entrega?',
        'faq.q3.answer': '¡Sí! Cada proyecto incluye 30 días de soporte gratuito. Después, ofrecemos planes de mantenimiento flexibles desde USD 15/mes. También entregamos documentación completa para que puedas gestionar el sistema independientemente.',
        'faq.q3.stats': '30 días de soporte incluido',
        'faq.q4.question': '¿Qué necesito para empezar?',
        'faq.q4.answer': 'Solo tres cosas: un problema de negocio claro que quieras resolver, acceso a los sistemas existentes (si aplica) y disponibilidad para una llamada de inicio de 30 minutos. Nosotros nos encargamos del resto.',
        'faq.q4.stats': 'Inicio en 24-48 horas',
        'faq.q5.question': '¿Quiénes son sus clientes típicos?',
        'faq.q5.answer': 'Trabajamos con startups y PyMEs ambiciosas en LATAM y EE.UU. Clientes que buscan escalar eficientemente, valoran la experiencia técnica y necesitan sistemas documentados y mantenibles.',
        'faq.q5.stats': 'Clientes en Uruguay y Argentina',
        'faq.q6.question': '¿Cómo manejan la seguridad y los datos?',
        'faq.q6.answer': 'Con prácticas security-first y experiencia real en entornos de alto cumplimiento: trabajamos bajo gestión de calidad ISO 9001 y con compliance PCI-DSS en pagos. Aplicamos cifrado, principio de mínimo privilegio y sistemas documentados y mantenibles que podés auditar.',
        'faq.q6.stats': 'Experiencia ISO 9001 · PCI-DSS',
        'contact.title': '¿Listo para Escalar tu Negocio?',
        'contact.subtitle': 'Contanos qué necesitás y seguimos la charla por WhatsApp. Te atiende MatchBot, nuestra propia plataforma de bots con IA: la misma que implementamos para nuestros clientes.',
        'contact.feat.response.title': 'Te atiende al instante',
        'contact.feat.response.desc': 'MatchBot toma tu consulta apenas la enviás, a cualquier hora. Un humano del equipo sigue la conversación en el día.',
        'contact.feat.commit.title': 'Sin Compromiso',
        'contact.feat.commit.desc': 'Consulta gratuita sin obligación. Te daremos consejos honestos incluso si no somos la opción ideal.',
        'contact.feat.start.title': 'Inicio Rápido',
        'contact.feat.start.desc': 'Si somos compatibles, podemos iniciar tu proyecto en 24-48 horas.',
        'contact.form.name': 'Nombre Completo',
        'contact.form.name.ph': 'Juan Pérez',
        'contact.form.email': 'Correo Electrónico',
        'contact.form.email.ph': 'juan@empresa.com',
        'contact.form.company': 'Nombre de la Empresa',
        'contact.form.company.ph': 'Tu Empresa',
        'contact.form.phone': 'Número de Teléfono',
        'contact.form.phone.ph': '+598 99 123 456',
        'contact.form.message': 'Cuéntanos sobre tu proyecto',
        'contact.form.message.ph': 'Describe el desafío de tu negocio y qué buscas lograr...',
        'contact.form.submit': 'Seguir por WhatsApp',
        'contact.form.sending': 'Abriendo WhatsApp...',
        'contact.form.email.fallback': '¿Preferís por correo? Escribinos directo',
        'contact.form.legal': 'Al enviar este formulario, aceptas nuestra política de privacidad y términos de servicio',
        'contact.wa.intro': 'Hola, les escribo desde la web de Digital Match Global.',
        'contact.mail.subject': 'Consulta desde la web',
        'contact.error.name': 'El nombre es requerido',
        'contact.error.email': 'El correo es requerido',
        'contact.error.email.invalid': 'Formato de correo inválido',
        'contact.error.company': 'El nombre de la empresa es requerido',
        'contact.error.phone': 'El teléfono es requerido',
        'contact.success.title': '¡Te abrimos WhatsApp!',
        'contact.success.desc': 'Tu consulta ya está escrita en el chat: solo tenés que enviarla. MatchBot te responde ahí mismo.',
        'contact.success.mail.title': '¡Te abrimos el correo!',
        'contact.success.mail.desc': 'Tu consulta ya está escrita en el mensaje: solo tenés que enviarla. Te respondemos dentro de las próximas 24 horas.',
        'contact.success.button': 'Hacer otra consulta',
        'footer.rights': 'Todos los derechos reservados',
        'footer.privacy': 'Política de Privacidad',
        'footer.terms': 'Términos de Servicio',
        'footer.data_deletion': 'Eliminación de Datos',
        'footer.matchbot': 'MatchBot ↗',
        'footer.description': 'Construyendo sistemas que escalan tu negocio a través de automatización, IA y desarrollo web.',
        'footer.legal.title': 'Legal',
        'footer.location': 'Con base en Uruguay',
        // "Experiencia" no es opcional: comunicamos ISO/PCI como experiencia, nunca como
        // certificación propia de la empresa (ver CLAUDE.md §7).
        'footer.security': 'Seguridad primero • Experiencia ISO 9001 · PCI-DSS • Documentado',
        'footer.contact.title': 'Contacto',
        'footer.contact.email': 'Escribinos',
        'footer.contact.whatsapp': 'WhatsApp',
        'footer.social.follow': 'Seguinos en',
        'footer.signature.madeBy': 'Hecho por'
    },
    en: {
        // ... MANTENER TODO LO ANTERIOR EN INGLÉS ...
        'nav.services': 'Services',
        'nav.about': 'About',
        'nav.results': 'Results',
        'nav.cases': 'Cases',
        'nav.process': 'Process',
        'nav.contact': 'Contact',
        'nav.menu': 'Menu',
        'nav.book': 'Book Consultation',
        'nav.tooltips.services': 'Explore automation solutions',
        'nav.tooltips.about': 'Meet the team behind it',
        'nav.tooltips.results': 'See client results',
        'nav.tooltips.cases': 'See our cases and projects',
        'nav.tooltips.process': 'Understand our methodology',
        'nav.tooltips.contact': 'Book consultation',

        // --- PORTFOLIO / CASES ---
        'portfolio.title': 'Cases & projects',
        'portfolio.subtitle': 'A selection of real work by industry. Each project, its own challenge and its own solution.',
        'portfolio.home.title': 'How we turn operational problems into digital solutions',
        'portfolio.home.subtitle': 'A selection of delivered projects to reduce manual work, connect tools and improve operations.',
        'portfolio.home.cta': 'View all cases',
        'portfolio.featured': 'Featured cases',
        'portfolio.more': 'More projects',
        'case.featured': 'Featured case',
        'case.eyebrow': 'Case study',
        'case.client': 'Client',
        'case.challenge': 'The challenge',
        'case.solution': 'The solution',
        'case.services': 'Services',
        'case.result': 'Result',
        'case.view': 'View case',
        'case.cta': "Let's talk about your project",
        'case.back': 'Back to cases',
        'case.prev': 'Previous project',
        'case.next': 'Next project',
        'case.contact.eyebrow': 'Contact',
        'case.contact.title': "Let's work together",
        'case.contact.subtitle': 'If you got this far, drop us a line — no strings attached.',
        'case.contact.cta': 'Get in touch',

        // --- CAMBIO AQUÍ (Hero Badge) ---
        'hero.badge': 'Automation • AI • Web Development',
        // Antes decía: 'Digital transformation • Automation • AI'

        'hero.title.part1': 'Build systems that',
        'hero.title.highlight': 'scale',
        'hero.title.part2': 'your business',
        'hero.subtitle': 'From bottleneck to breakthrough in as little as 7-14 days',
        'hero.cta.book': 'Book Strategy Call',
        'hero.cta.work': 'View Our Work',

        // --- ABOUT / WHO WE ARE (anonymous, differentiators — NOT services) ---
        'about.eyebrow': 'The team behind Digital Match Global',
        'about.title': 'Recover the hours your team loses on manual tasks.',
        'about.subtitle': 'Engineering applied to your day-to-day: we automate processes, connect systems and build tools so your team works with less friction.',
        'about.diff1.title': '14+ years',
        'about.diff1.desc': 'Of experience in automation, AI, and development.',
        'about.diff2.title': 'Enterprise & government',
        'about.diff2.desc': 'Real experience across the private and public sectors.',
        'about.diff3.title': 'Security & compliance',
        'about.diff3.desc': 'Experience under ISO 9001 and PCI-DSS compliance in data handling.',
        'about.diff4.title': 'Certified',
        'about.diff4.desc': 'In UiPath, Microsoft & IBM.',
        'about.tools_label': 'Technology stack',
        'stack.subtitle': 'We cover the whole pipeline, from automation to the cloud.',
        'stack.rpa': 'Automation / RPA',
        'stack.ai': 'AI & Data',
        'stack.dev': 'Development',
        'stack.cloud': 'Cloud & Infrastructure',
        'stack.data': 'Databases',
        'stack.integrations': 'Integrations & APIs',

        // ... MANTENER EL RESTO EN INGLÉS ...
        'keywords.ml': 'Machine Learning',
        'keywords.automation': 'Process Automation',
        'keywords.api': 'API Integration',
        'keywords.cloud': 'Cloud Infrastructure',
        'keywords.analytics': 'Data Analytics',
        'keywords.ai': 'AI Solutions',
        'proof.m1.label': 'Years of Experience',
        'proof.m2.label': 'Automated Processes',
        'proof.m3.label': 'Days from diagnosis to solution',
        'services.main_title': 'Our Services',
        'services.main_subtitle': 'Comprehensive solutions to scale your business operations',
        'services.cta_button': 'View Case Study',
        // --- Our own product: MatchBot ---
        'services.matchbot.eyebrow': 'Our own product',
        'services.matchbot.desc': 'MatchBot is our AI-powered WhatsApp bot platform: each business connects its own number and automates its conversations. Built on our official Meta Tech Provider integration.',
        'services.matchbot.cta': 'Discover MatchBot',
        'services.auto.title': 'Process Automation (RPA)',
        'services.auto.headline': 'Eliminate 80% manual tasks',
        'services.auto.desc': 'RPA bots that turn repetitive workflows into systems running 24/7, without human intervention (UiPath · Rocketbot · Power Automate).',
        'services.auto.f1': 'Custom RPA bots (UiPath · Rocketbot)',
        'services.auto.f2': 'Data integration & synchronization',
        'services.auto.f3': 'Email & notification automation',
        'services.auto.f4': 'Report generation systems',
        'services.ai.title': 'AI Assistants',
        'services.ai.headline': '24/7 customer support automation',
        'services.ai.desc': 'Deploy intelligent chatbots that handle customer inquiries, bookings, and support tickets automatically.',
        'services.ai.f1': 'Natural language processing',
        'services.ai.f2': 'Multi-channel integration',
        'services.ai.f3': 'Custom training on your data',
        'services.ai.f4': 'Analytics & insights dashboard',
        'services.web.title': 'Web Products',
        'services.web.headline': 'Revenue-generating platforms',
        'services.web.desc': 'Build scalable web applications and internal tools that drive business growth and efficiency.',
        'services.web.f1': 'MVP development (from 7-14 days)',
        'services.web.f2': 'Mobile-responsive design',
        'services.web.f3': 'API & third-party integrations',
        'services.web.f4': 'Security & compliance built-in',
        'services.consulting.title': 'Consulting & Training',
        'services.consulting.headline': 'Digital transformation & technology adoption',
        'services.consulting.desc': 'We advise and train your team: from process assessment to training sessions on automation and AI.',
        'services.consulting.f1': 'Process & opportunity assessment (RPA/AI)',
        'services.consulting.f2': 'Digital transformation roadmap',
        'services.consulting.f3': 'Team training sessions',
        'services.consulting.f4': 'AI & automation adoption',

        // --- Engagement models ---
        'services.models.title': 'How you can work with us',
        'services.models.subtitle': 'Pick the format that best fits your need.',
        'services.models.project.title': 'By project',
        'services.models.project.desc': 'Turnkey solution, with a working MVP from 7-14 days depending on complexity.',
        'services.models.hourly.title': 'By the hour',
        'services.models.hourly.desc': 'Hour bank for RPA, automation and development, on demand.',
        'services.models.consulting.title': 'Consulting',
        'services.models.consulting.desc': 'Assessment, architecture and a digital transformation roadmap.',
        'services.models.training.title': 'Training sessions',
        'services.models.training.desc': 'Train your team in RPA, AI and technology adoption.',

        // --- Certifications ---
        'certs.title': 'Certifications that back us',
        'certs.subtitle': 'Official training that backs how we work.',
        'certs.uipath': 'UiPath RPA Developer',
        'certs.rocketbot': 'Rocketbot Suite (RPA)',
        'certs.microsoft': 'Microsoft Azure AI',
        'certs.ibm': 'IBM Data Science',
        'certs.meta.title': 'Verified Meta Tech Provider',
        'certs.meta.subtitle': 'Official WhatsApp Business API integration — business verified and Meta App Review approved.',

        'technical.title': 'How we do it',
        'technical.subtitle': 'Enterprise standards and typical outcomes in each area of work',
        'technical.outcomes_title': 'Typical Outcomes',
        'technical.auto.title': 'Process Automation',
        'technical.auto.desc': 'Eliminate repetitive tasks and streamline operations with intelligent automation systems.',
        'technical.auto.impact': 'High Operational Efficiency', 
        'technical.auto.out1': 'Reduce manual data entry by 90%',
        'technical.auto.out2': 'Cut processing time from hours to minutes',
        'technical.auto.out3': 'Eliminate human error in routine tasks',
        'technical.auto.out4': 'Free up team for strategic work',
        'technical.ai.title': 'AI Assistants',
        'technical.ai.desc': 'Deploy intelligent chatbots and virtual assistants for 24/7 customer engagement.',
        'technical.ai.impact': 'Guaranteed 24/7 Support', 
        'technical.ai.out1': 'Handle 80% of customer inquiries automatically',
        'technical.ai.out2': 'Reduce response time from hours to seconds',
        'technical.ai.out3': 'Scale support without hiring',
        'technical.ai.out4': 'Improve customer satisfaction scores',
        'technical.web.title': 'Web Products',
        'technical.web.desc': 'Build revenue-generating platforms and internal tools that drive business growth.',
        'technical.web.impact': 'High Performance & SEO', 
        'technical.web.out1': 'First MVP from 7-14 days, by complexity',
        'technical.web.out2': 'Scale to thousands of users',
        'technical.web.out3': 'Integrate with existing systems',
        'technical.web.out4': 'Mobile-optimized and secure',
        'faq.title': 'Frequently Asked Questions',
        'faq.subtitle': 'Everything you need to know about working with us',
        'faq.q1.question': 'How long does it take to deliver a project?',
        'faq.q1.answer': 'It depends on complexity: most projects start being delivered from 7-14 days after kickoff. We follow an agile methodology with daily updates and iterative releases; for larger projects, the first working version arrives within a few weeks.',
        'faq.q1.stats': 'First MVP: from 7-14 days',
        'faq.q2.question': 'What is your work process?',
        'faq.q2.answer': 'We start with a strategy call to understand your needs, then create a detailed technical specification. Development happens in sprints with daily updates via Slack/WhatsApp. You get access to a staging environment to test features as they are built. Final delivery includes complete documentation, training, and 30 days of support.',
        'faq.q2.stats': 'Daily communication during the project',
        'faq.q3.question': 'Do you provide post-delivery support?',
        'faq.q3.answer': 'Yes! Every project includes 30 days of free support and bug fixes. After that, we offer flexible maintenance plans starting at USD 15/month. We also provide training for your team and comprehensive documentation so you can manage the system independently if needed.',
        'faq.q3.stats': '30 days of support included',
        'faq.q4.question': 'What do I need to get started?',
        'faq.q4.answer': 'Just three things: a clear business problem you want to solve, access to any existing systems we need to integrate with, and availability for 30 minutes kickoff call. We handle everything else including project management, design, development, testing, and deployment.',
        'faq.q4.stats': 'Start in 24-48 hours',
        'faq.q5.question': 'Who are your typical clients?',
        'faq.q5.answer': 'We work with ambitious startups and SMEs in LATAM and US. Our clients are typically experiencing operational bottlenecks, looking to scale efficiently, and value technical expertise over cheap alternatives. They need fast implementation with documented, maintainable systems.',
        'faq.q5.stats': 'Clients in Uruguay and Argentina',
        'faq.q6.question': 'How do you handle security and data?',
        'faq.q6.answer': 'With security-first practices and real experience in high-compliance environments: we work under ISO 9001 quality management and with PCI-DSS compliance in payments. We apply encryption, least-privilege access, and documented, maintainable systems you can audit.',
        'faq.q6.stats': 'ISO 9001 · PCI-DSS experience',
        'contact.title': "Ready to Scale Your Business?",
        'contact.subtitle': 'Tell us what you need and we continue on WhatsApp. MatchBot takes it from there — our own AI bot platform, the same one we deploy for our clients.',
        'contact.feat.response.title': 'Answered instantly',
        'contact.feat.response.desc': 'MatchBot picks up your inquiry the moment you send it, at any hour. Someone from the team follows up the same day.',
        'contact.feat.commit.title': 'No Commitment',
        'contact.feat.commit.desc': "Free consultation with no obligation. We'll provide honest advice even if we're not the right fit",
        'contact.feat.start.title': 'Quick Start',
        'contact.feat.start.desc': "If we're a good match, we can start your project within 24-48 hours",
        'contact.form.name': 'Full Name',
        'contact.form.name.ph': 'John Doe',
        'contact.form.email': 'Email',
        'contact.form.email.ph': 'john@company.com',
        'contact.form.company': 'Company Name',
        'contact.form.company.ph': 'Your Company',
        'contact.form.phone': 'Phone Number',
        'contact.form.phone.ph': '+1 (555) 000-0000',
        'contact.form.message': 'Tell us about your project',
        'contact.form.message.ph': "Describe your business challenge and what you're looking to achieve...",
        'contact.form.submit': 'Continue on WhatsApp',
        'contact.form.sending': 'Opening WhatsApp...',
        'contact.form.email.fallback': 'Prefer email? Write to us directly',
        'contact.form.legal': 'By submitting this form, you agree to our privacy policy and terms of service',
        'contact.wa.intro': "Hi, I'm writing from the Digital Match Global website.",
        'contact.mail.subject': 'Inquiry from the website',
        'contact.error.name': 'Name is required',
        'contact.error.email': 'Email is required',
        'contact.error.email.invalid': 'Invalid email format',
        'contact.error.company': 'Company name is required',
        'contact.error.phone': 'Phone number is required',
        'contact.success.title': 'WhatsApp is open!',
        'contact.success.desc': 'Your inquiry is already written in the chat — just hit send. MatchBot replies right there.',
        'contact.success.mail.title': 'Your email is open!',
        'contact.success.mail.desc': 'Your inquiry is already written in the message — just hit send. We reply within 24 hours.',
        'contact.success.button': 'Send another inquiry',
        'footer.rights': 'All rights reserved',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.data_deletion': 'Data Deletion',
        'footer.matchbot': 'MatchBot ↗',
        'footer.description': 'Building systems that scale your business through automation, AI, and web development',
        'footer.legal.title': 'Legal',
        'footer.location': 'Based in Uruguay',
        'footer.security': 'Security-first • ISO 9001 · PCI-DSS experience • Documented',
        'footer.contact.title': 'Contact',
        'footer.contact.email': 'Email us',
        'footer.contact.whatsapp': 'WhatsApp',
        'footer.social.follow': 'Follow us on',
        'footer.signature.madeBy': 'Made by'
    },
    };

    export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguageState] = useState<Language>('es');

    useEffect(() => {
        const savedLang = localStorage.getItem('preferred-language') as Language;
        if (savedLang && (savedLang === 'es' || savedLang === 'en')) {
        setLanguageState(savedLang);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('preferred-language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key as keyof typeof translations.es] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
        {children}
        </LanguageContext.Provider>
    );
    };

    export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
    };